todo: cuda_version_1 cuda_version_2 cuda_version_3 cuda_version_4 cuda_version_5
cuda_version_1: cuda_version_1.cu
	nvcc --ptxas-options=-v -O3 cuda_version_1.cu -o cuda_version_1 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
cuda_version_2: cuda_version_2.cu
	nvcc --ptxas-options=-v -O3 cuda_version_2.cu -o cuda_version_2 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
cuda_version_3: cuda_version_3.cu
	nvcc --ptxas-options=-v -O3 cuda_version_3.cu -o cuda_version_3 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
cuda_version_4: cuda_version_4.cu
	nvcc --ptxas-options=-v -O3 cuda_version_4.cu -o cuda_version_4 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
cuda_version_5: cuda_version_5.cu
	nvcc --ptxas-options=-v -O3 cuda_version_5.cu -o cuda_version_5 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp

clean:
	rm cuda_version_1 cuda_version_2 cuda_version_3 cuda_version_4 cuda_version_5
