todo: cuda cuda_2 cuda_3 test
cuda: cuda_1.cu
	nvcc --ptxas-options=-v -O3 cuda_1.cu -o cuda -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
cuda_2: cuda_2.cu
	nvcc --ptxas-options=-v -O3 cuda_2.cu -o cuda_2 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp

cuda_3: cuda_3.cu
	nvcc --ptxas-options=-v -O3 cuda_3.cu -o cuda_3 -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp


test: test.cu
	nvcc --ptxas-options=-v -O3 test.cu -o test -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp

clean:
	rm cuda cuda_2 cuda_3 test
